-------------
-- "ADMIN" --
-------------

GRANT CONSOLE_DEVELOPER TO WKSP_RAG;
GRANT DWROLE            TO WKSP_RAG;
GRANT OML_DEVELOPER     TO WKSP_RAG;
GRANT RESOURCE          TO WKSP_RAG;

ALTER USER WKSP_RAG DEFAULT ROLE CONSOLE_DEVELOPER, DWROLE, OML_DEVELOPER;

GRANT EXECUTE ON DBMS_CLOUD TO WKSP_RAG;