GRANT CONSOLE_DEVELOPER TO wksp_demo;
GRANT DWROLE TO wksp_demo;
GRANT OML_DEVELOPER TO wksp_demo;
GRANT RESOURCE TO wksp_demo;
ALTER USER wksp_demo DEFAULT ROLE CONSOLE_DEVELOPER, DWROLE, OML_DEVELOPER;