CREATE TABLE RAG_BOOKS (
    FILE_ID      NUMBER,
    FILE_NAME    VARCHAR2(100),
    FILE_CONTENT BLOB
);

CREATE TABLE RAG_VECTORS (
    EMBED_ID     NUMBER,
    EMBED_DATA   VARCHAR2(4000),
    EMBED_VECTOR VECTOR,
    FILE_ID      NUMBER
);