ORDER BY VECTOR_DISTANCE(V, TO_VECTOR('[1.1, 2.2]'), MANHATTAN)
ORDER BY L1_DISTANCE(V, TO_VECTOR('[1.1, 2.2]'))

ORDER BY VECTOR_DISTANCE(V, TO_VECTOR('[1.1, 2.2]'), EUCLIDEAN)
ORDER BY L2_DISTANCE(V, TO_VECTOR('[1.1, 2.2]'))

ORDER BY VECTOR_DISTANCE(V, TO_VECTOR('[1.1, 2.2]'), COSINE)
ORDER BY COSINE_DISTANCE(V, TO_VECTOR('[1.1, 2.2]'))

ORDER BY VECTOR_DISTANCE(V, TO_VECTOR('[1.1, 2.2]'), DOT)
ORDER BY INNER_PRODUCT(V, TO_VECTOR('[1.1, 2.2]'))

